spring:
  application:
    name: queryDistribution
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://localhost:27017/dqs}
      index-partitions:
        group-by: 64

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
