spring:
  application:
    name: queryDistribution
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://localhost:27017/dqs}
      index-partitions:
        group-by: ${INDEX_PARTITION_GROUP_BY:32}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: AWS_MSK_IAM
        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

tenants: ${TENANTS}
incoming-sub-queries-partitions: ${NUMBER_OF_PARTITIONS:1}
worker_count_for_dqs_task : ${WORKER_COUNT_FOR_DQS_TASK:1}
use_dqs_task : ${USE_DQS_TASK:false}

