{{- range .Values.TENANTS }}
{{- $partitionKey := printf "NUMBER_OF_PARTITIONS_%s" (upper .) }}
{{- $partitions := index $.Values $partitionKey }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "query-distribution-deployment-%s" . }}
  namespace: {{ printf "%s-%s" $.Values.namespace . }}
  labels:
    app: query-distribution
spec:
  replicas: {{ $.Values.NUMBER_OF_WORKERS }}
  selector:
    matchLabels:
      app: query-distribution
  template:
    metadata:
      labels:
        app: query-distribution
    spec:
      serviceAccountName: {{ printf "dqs-query-distribution-%s-service-account" . }}
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: query-distribution-container
          image: {{ $.Values.IMAGE_URI }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NUMBER_OF_PARTITIONS
              value: "{{ $partitions }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ $.Values.KAFKA_BOOTSTRAP_SERVERS }}
            - name: MONGO_DB_URL
              value: {{ $.Values.MONGO_DB_URL }}
            - name: TENANTS
              value: {{ . }}
            - name: INDEX_PARTITION_GROUP_BY
              value: "{{ $.Values.INDEX_PARTITION_GROUP_BY }}"
---
{{- end }}